default: &default
  pool: 5
  timeout: 5000
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  adapter: mysql2
  username: root
  password: root
  database: greenlight_development
test:
  <<: *default
  adapter: mysql2
  username: root
  password: root
  database: greenlight_test

# Use sqlite in production by default. Greenlight supports
production:
  <<: *default
  adapter: <%= ENV['DB_ADAPTER'] || 'mysql2' %>
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] || 'greenlight_production' %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
